### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by emmtte** [sindresorhus/capture-website-cli#23]
````
capture-website https://sindresorhus.com --output=screenshot.png
Error: Failed to launch the browser process!
/usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome: /usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/.local-chromium/linux-722234/chrome-linux/chrome : ne peut exécuter le fichier binaire


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/Launcher.js:750:14)
    at Interface.<anonymous> (/usr/local/lib/node_modules/capture-website-cli/node_modules/puppeteer/lib/Launcher.js:739:50)
    at Interface.emit (events.js:317:22)
    at Interface.close (readline.js:410:8)
    at Socket.onend (readline.js:188:10)
    at Socket.emit (events.js:317:22)
    at endReadableNT (_stream_readable.js:1215:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
````

and this page not exist

````
https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md
````

**Comment by omkar4345** [comment]
Hi Emmtte,

Did you get any solution. I am also facing similar issue.

Thanks & regards,
Omkar

**Comment by emmtte** [comment]
Hi omkar.

Not yet and developper not respond me

I'm waiting...

**Comment by omkar4345** [comment]
Dear Emmtte,

My project issue due to chromium. Chromium was not getting downloaded with the given procedure and not given error during the execution. I noticed chromium directory was not present under puppeteer directory.

Seems it was due to my internet restrictions. Chromium started downloading after I refired the "npm i puppeteer" command.

Thanks for support,

Cheers........
Omkar

**Comment by omkar4345** [comment]
Dear All,

My project issue due to chromium. Chromium was not getting downloaded with the given procedure and not given error during the same. I noticed chromium directory was not present under puppeteer directory.

Seems it was due to my internet restrictions. Chromium started downloading after I refired the "npm i puppeteer" command.

Thanks for support,

Cheers........
Omkar

**Comment by sindresorhus** [comment]
This is a problem with installing Puppeteer, which is a dependency here.

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
